"""empty message

Revision ID: 33335ca606c9
Revises: f9e5bcd219de
Create Date: 2016-05-11 15:52:28.507140

"""

# revision identifiers, used by Alembic.
revision = '33335ca606c9'
down_revision = 'f9e5bcd219de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'event_type', ['event_type'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'event_type')
    ### end Alembic commands ###
